apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: cristiancapa20/usuarios_front:v12 # Reemplaza esto con la imagen de tu aplicación React
          ports:
            - containerPort: 3000
