apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  MONGO_URL: bW9uZ29kYjovL21vbmdvZGI6MjcwMTcvZWFzeWhvdXNlCg== # Base64 encoded value of "mongodb://mongo-db-service:27017/easyhouse"
